"""FastAPI service wrapping the A1 chest X-ray pneumonia classifier.

Endpoints
    GET  /              the web UI
    GET  /health        liveness + model status
    GET  /metadata      model version, threshold, class names, limits
    POST /predict       JSON body: {"image_url": "https://..."}
    POST /predict/file  multipart upload, field name "file"
    GET  /docs          interactive OpenAPI docs (generated by FastAPI)
"""

from __future__ import annotations

import logging
import time
import uuid
from contextlib import asynccontextmanager

from fastapi import FastAPI, File, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from . import config
from .images import ImageIntakeError, decode_image, load_image_from_url
from .logging_config import configure_logging
from .model import CLASS_NAMES, ModelNotLoadedError, classifier
from .schemas import ErrorResponse, HealthResponse, PredictRequest, PredictResponse

configure_logging()
log = logging.getLogger("xray.api")

STATIC_DIR = config.APP_ROOT / "static"


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the model once at startup rather than on the first request.

    Cloud Run counts a container as ready when it accepts traffic on $PORT, so
    loading here means the first user request doesn't pay the ~1s load cost.
    """
    log.info(
        "Starting up",
        extra={
            "json_fields": {
                "model_path": str(config.MODEL_PATH),
                "threshold": config.DECISION_THRESHOLD,
                "port": config.PORT,
            }
        },
    )
    try:
        classifier.load()
        classifier.warmup()
    except Exception:
        # Log loudly but still start, so /health can report the problem instead
        # of the container crash-looping with the reason buried in the logs.
        log.exception("Model failed to load; /predict will return 503")

    yield
    log.info("Shutting down")


app = FastAPI(
    title="Chest X-Ray Pneumonia Classifier",
    description=(
        "Serves the fine-tuned ResNet18 from Assignment 1. Submit a chest X-ray "
        "by URL or file upload and receive a NORMAL / PNEUMONIA prediction with "
        "the underlying probability.\n\n"
        "**Screening aid for coursework only — not a diagnostic device.**"
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=config.ALLOWED_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


@app.middleware("http")
async def log_requests(request: Request, call_next):
    """One structured log line per request: path, status, latency, request id."""
    request_id = str(uuid.uuid4())[:8]
    started = time.perf_counter()

    response = await call_next(request)

    duration_ms = round((time.perf_counter() - started) * 1000, 2)
    response.headers["X-Request-ID"] = request_id

    # Health checks fire constantly; keep them at DEBUG so they don't bury the
    # prediction traffic in the log viewer.
    level = logging.DEBUG if request.url.path == "/health" else logging.INFO
    log.log(
        level,
        f"{request.method} {request.url.path} -> {response.status_code}",
        extra={
            "json_fields": {
                "request_id": request_id,
                "method": request.method,
                "path": request.url.path,
                "status": response.status_code,
                "duration_ms": duration_ms,
            }
        },
    )
    return response


@app.exception_handler(ImageIntakeError)
async def image_intake_handler(request: Request, exc: ImageIntakeError):
    log.warning(
        "Rejected image input",
        extra={"json_fields": {"path": request.url.path, "reason": str(exc)}},
    )
    return JSONResponse(status_code=400, content={"detail": str(exc)})


# --- Routes ----------------------------------------------------------------


@app.get("/", include_in_schema=False)
async def index():
    """Serve the prediction page."""
    return FileResponse(STATIC_DIR / "index.html")


@app.get("/health", response_model=HealthResponse, tags=["ops"])
async def health():
    """Liveness probe. Returns 200 while the process is up; `model_loaded`
    tells you whether it can actually serve predictions."""
    return HealthResponse(
        status="ok" if classifier.is_loaded else "degraded",
        model_loaded=classifier.is_loaded,
        model_version=classifier.version,
        threshold=classifier.threshold,
    )


@app.get("/metadata", tags=["ops"])
async def metadata():
    """What this deployment is running, for the UI and for debugging."""
    return {
        "model_version": classifier.version,
        "architecture": "ResNet18 (ImageNet-pretrained, fine-tuned end-to-end)",
        "task": "binary image classification",
        "classes": list(CLASS_NAMES),
        "threshold": classifier.threshold,
        "input_size": [224, 224],
        "max_image_bytes": config.MAX_IMAGE_BYTES,
        "known_limitation": (
            "On the held-out test set the model reached 84.9% accuracy and 0.822 "
            "macro F1, but recall on NORMAL cases was 60.7% — it over-flags "
            "healthy chests as PNEUMONIA. Treat a PNEUMONIA result as a prompt "
            "to look closer, not as a finding."
        ),
    }


@app.post(
    "/predict",
    response_model=PredictResponse,
    responses={400: {"model": ErrorResponse}, 503: {"model": ErrorResponse}},
    tags=["prediction"],
)
async def predict(payload: PredictRequest):
    """Classify a chest X-ray given a public image URL.

    Example body: `{"image_url": "https://example.com/chest-xray.jpeg"}`
    """
    image = load_image_from_url(payload.image_url)
    result = _run_prediction(image, source="url")
    log.info(
        "Prediction served",
        extra={
            "json_fields": {
                "source": "url",
                "image_url": payload.image_url[:200],
                "prediction": result["prediction"],
                "probability_pneumonia": result["probability_pneumonia"],
                "inference_ms": result["inference_ms"],
            }
        },
    )
    return result


@app.post(
    "/predict/file",
    response_model=PredictResponse,
    responses={400: {"model": ErrorResponse}, 503: {"model": ErrorResponse}},
    tags=["prediction"],
)
async def predict_file(file: UploadFile = File(...)):
    """Classify an uploaded chest X-ray. This is what the web UI calls."""
    raw = await file.read()
    image = decode_image(raw)
    result = _run_prediction(image, source="upload")
    log.info(
        "Prediction served",
        extra={
            "json_fields": {
                "source": "upload",
                "filename": file.filename,
                "bytes": len(raw),
                "prediction": result["prediction"],
                "probability_pneumonia": result["probability_pneumonia"],
                "inference_ms": result["inference_ms"],
            }
        },
    )
    return result


def _run_prediction(image, source: str) -> dict:
    try:
        return classifier.predict(image)
    except ModelNotLoadedError as exc:
        log.error("Prediction attempted with no model loaded")
        raise HTTPException(
            status_code=503,
            detail="Model is not loaded. Check the container logs and /health.",
        ) from exc
    except Exception as exc:
        log.exception("Inference failed", extra={"json_fields": {"source": source}})
        raise HTTPException(status_code=500, detail="Inference failed.") from exc


# Mounted last so it doesn't shadow the routes above.
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


if __name__ == "__main__":
    # Convenience for `python -m app.main`; the container uses the uvicorn CLI.
    import uvicorn

    uvicorn.run("app.main:app", host="0.0.0.0", port=config.PORT, log_config=None)
